version: "3.7"

services:
  marklogic:
    image: marklogiccommunity/marklogic:latest
    volumes:
      - type: volume
        source: marklogic_data
        target: /data
    ports:
      - "7997:7997/tcp"
      - "8000-8002:8000-8002/tcp"
      - "8010-8011:8010-8011/tcp"
      - "8013:8013/tcp"

  nifi:
    image: marklogiccommunity/nifi:latest
    links: 
      - marklogic
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: volume
        source: nifi_data
        target: /opt/nifi/nifi-1.7.1
    ports:
    - "8080:8080/tcp"

  quick-start:
    image: marklogiccommunity/data-hub-quick-start:latest
    links: 
      - marklogic
    volumes:
      - type: bind
        source: .
        target: /usr/src/app/data-hub
    ports:
    - "8081:8080/tcp"

  gradle:
    image: gradle:alpine
    depends_on:
      - "marklogic"
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
    working_dir: /usr/src/app
    command: "gradle -PmlHost=marklogic mlInit mlInstallAdmin"

volumes:
  marklogic_data:
  nifi_data:
