version: "3.6"

services:
  marklogic:
    image: marklogic.azurecr.io/marklogic:latest
    volumes:
      - type: volume
        source: marklogic_data
        target: /data
    ports:
      - "7997-8020:7997-8020/tcp"

  gradle:
    image: gradle:alpine
    volumes:
      - type: bind
        source: .
        target: /home/gradle/project
    working_dir: /home/gradle/project
    command: "gradle -PmlHost=marklogic mlInit mlInstallAdmin mlDeploy install"

volumes:
  marklogic_data:
