version: "3.7"

services:
  marklogic:
    image: marklogiccommunity/marklogic:latest
    volumes:
      - type: volume
        source: marklogic_data
        target: /data
    ports:
      - "7997:7997/tcp"
      - "8000-8002:8000-8002/tcp"
      - "8003:8003/tcp"
      
  gradle:
    image: gradle:alpine
    depends_on:
      - "marklogic"
    volumes:
      - type: bind
        source: ./
        target: /home/gradle/project
    working_dir: /home/gradle/project
    command: "gradle -PmlHost=marklogic mlInit mlInstallAdmin mlDeploy"

volumes:
  marklogic_data:
