version: "3.7"

services:
  marklogic:
    image: gumball/marklogic:latest
    volumes:
      - type: volume
        source: marklogic_data
        target: /data
    ports:
      - "7997:7997/tcp"
      - "8000-8002:8000-8002/tcp"
      - "8063:8063/tcp"

  nifi:
    image: gumball/nifi:latest
    links: 
      - marklogic
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: volume
        source: nifi_data
        target: /opt/nifi/nifi-1.7.1
    ports:
    - "8080:8080/tcp"
      
  gradle:
    image: gradle:alpine
    depends_on:
      - "marklogic"
    volumes:
      - type: bind
        source: ./
        target: /home/gradle/project
    working_dir: /home/gradle/project
    command: "gradle -PmlHost=marklogic mlInit mlInstallAdmin mlDeploy"

volumes:
  marklogic_data:
  nifi_data:
